services:
  pycharm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pycharm
    image: ${REGISTRY_BASE_URL}/${IMAGE_OWNER}/${IMAGE_NAME}:${IMAGE_TAG}
    network_mode: host
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=/run/user/${UID:-1000}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - QT_QPA_PLATFORM=xcb
    devices:
      - /dev/snd:/dev/snd
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    volumes:
      - /run/user/${PUID:-1000}/${WAYLAND_DISPLAY}:/run/user/${PUID:-1000}/${WAYLAND_DISPLAY}:ro
      - /run/user/${PUID:-1000}/pulse:/run/user/${PUID:-1000}/pulse:rw
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro

      - ./mount/PycharmProjects:/home/${CONTAINER_USERNAME}/PycharmProjects
      - ./mount/.config/JetBrains:/home/${CONTAINER_USERNAME}/.config/JetBrains
      - ./mount/.cache:/home/${CONTAINER_USERNAME}/.cache
      - ./mount/.ssh:/home/${CONTAINER_USERNAME}/.ssh
      - ./mount/.local/share/JetBrains:/home/${CONTAINER_USERNAME}/.local/share/JetBrains
      - ./mount/.java/.userPrefs/jetbrains:/home/${CONTAINER_USERNAME}/.java/.userPrefs/jetbrains

    shm_size: 2g
    security_opt:
      - seccomp=unconfined

